use std::collections::BTreeSet;
use std::fmt::Write;

use anyhow::Result;

use crate::model::{
    Canister, Case, Definition, DefinitionKind, Field, Method, MethodKind, Program, SwiftType,
};

pub fn render(program: &Program) -> Result<String> {
    let mut output = String::from(
        "// Generated by ic-candid-swift-bindgen 0.1.1. Do not edit.\n\nimport Foundation\nimport ICNativeClient\n",
    );
    let Some(support_owner) = program.canisters.first() else {
        anyhow::bail!("cannot render bindings without a canister");
    };
    for (index, canister) in program.canisters.iter().enumerate() {
        for definition in &canister.definitions {
            output.push('\n');
            render_definition(&mut output, definition)?;
        }
        render_client(
            &mut output,
            canister,
            &support_owner.client_name,
            index == 0,
        )?;
    }
    Ok(output)
}

fn render_typed_decoder(output: &mut String) -> Result<()> {
    output.push_str(
        r#"

    enum _ICBindgenSupport {
        static func decode<T: CandidConvertible>(
            _ typedValue: CandidTypedValue,
            as type: T.Type,
            context: String
        ) throws -> T {
            guard typesEquivalent(typedValue.type, T.candidType) else {
                throw ICClientError.invalidCandid("\(context): declared type does not match \(T.candidType)")
            }
            do {
                return try T(candidValue: typedValue.value)
            } catch {
                throw ICClientError.invalidCandid("\(context): \(error.localizedDescription)")
            }
        }

        private static func typesEquivalent(_ lhs: CandidType, _ rhs: CandidType) -> Bool {
            typesEquivalent(lhs, rhs, bindings: [:], reverseBindings: [:])
        }

        private static func typesEquivalent(
            _ lhs: CandidType,
            _ rhs: CandidType,
            bindings: [UInt32: UInt32],
            reverseBindings: [UInt32: UInt32]
        ) -> Bool {
            switch (lhs, rhs) {
            case (.null, .null), (.bool, .bool), (.nat, .nat), (.int, .int),
                 (.nat8, .nat8), (.nat16, .nat16), (.nat32, .nat32), (.nat64, .nat64),
                 (.int8, .int8), (.int16, .int16), (.int32, .int32), (.int64, .int64),
                 (.float32, .float32), (.float64, .float64), (.text, .text),
                 (.principal, .principal):
                return true
            case let (.optional(lhsChild), .optional(rhsChild)),
                 let (.vector(lhsChild), .vector(rhsChild)):
                return typesEquivalent(
                    lhsChild,
                    rhsChild,
                    bindings: bindings,
                    reverseBindings: reverseBindings
                )
            case let (.record(lhsFields), .record(rhsFields)),
                 let (.variant(lhsFields), .variant(rhsFields)):
                guard lhsFields.count == rhsFields.count else { return false }
                return zip(lhsFields, rhsFields).allSatisfy { lhsField, rhsField in
                    lhsField.id == rhsField.id && typesEquivalent(
                        lhsField.type,
                        rhsField.type,
                        bindings: bindings,
                        reverseBindings: reverseBindings
                    )
                }
            case let (.recursive(lhsID, lhsBody), .recursive(rhsID, rhsBody)):
                if let existing = bindings[lhsID], existing != rhsID { return false }
                if let existing = reverseBindings[rhsID], existing != lhsID { return false }
                var nestedBindings = bindings
                var nestedReverseBindings = reverseBindings
                nestedBindings[lhsID] = rhsID
                nestedReverseBindings[rhsID] = lhsID
                return typesEquivalent(
                    lhsBody,
                    rhsBody,
                    bindings: nestedBindings,
                    reverseBindings: nestedReverseBindings
                )
            case let (.reference(lhsID), .reference(rhsID)):
                return bindings[lhsID] == rhsID && reverseBindings[rhsID] == lhsID
            default:
                return false
            }
        }
    }
"#,
    );
    Ok(())
}

fn render_definition(output: &mut String, definition: &Definition) -> Result<()> {
    match &definition.kind {
        DefinitionKind::Alias(ty) => {
            writeln!(
                output,
                "public typealias {} = {}",
                escaped(&definition.name),
                swift_type(ty)
            )?;
        }
        DefinitionKind::Record(fields) => render_record(output, definition, fields)?,
        DefinitionKind::Variant(cases) => render_variant(output, definition, cases)?,
    }
    Ok(())
}

fn render_record(output: &mut String, definition: &Definition, fields: &[Field]) -> Result<()> {
    let kind = if definition.recursive {
        "final class"
    } else {
        "struct"
    };
    writeln!(
        output,
        "public {kind} {}: CandidConvertible {{",
        escaped(&definition.name)
    )?;
    for field in fields {
        writeln!(
            output,
            "    public let {}: {}",
            escaped(&field.swift_name),
            swift_type(&field.ty)
        )?;
    }
    if !fields.is_empty() {
        output.push_str("\n    public init(\n");
        for (index, field) in fields.iter().enumerate() {
            let comma = if index + 1 == fields.len() { "" } else { "," };
            writeln!(
                output,
                "        {}: {}{}",
                escaped(&field.swift_name),
                swift_type(&field.ty),
                comma
            )?;
        }
        output.push_str("    ) {\n");
        for field in fields {
            let member = escaped(&field.swift_name);
            writeln!(output, "        self.{member} = {member}")?;
        }
        output.push_str("    }\n");
    } else {
        output.push_str("\n    public init() {}\n");
    }

    let recursion_id = recursion_id(&definition.name);
    output.push_str("\n    private static let fields: [CandidField] = [\n");
    for field in fields {
        writeln!(
            output,
            "        CandidField(id: {}, type: {}),",
            field.label.id(),
            candid_type(&field.ty, &definition.name, recursion_id)
        )?;
    }
    output.push_str("    ]\n\n");
    if definition.recursive {
        writeln!(
            output,
            "    public static let candidType = CandidType.recursive(id: {recursion_id}, body: .record(fields))"
        )?;
    } else {
        output.push_str("    public static let candidType = CandidType.record(fields)\n");
    }

    if definition.recursive {
        output.push_str("\n    public required init(candidValue: CandidValue) throws {\n");
    } else {
        output.push_str("\n    public init(candidValue: CandidValue) throws {\n");
    }
    output.push_str("        let record = try CandidRecord(candidValue)\n");
    for field in fields {
        let member = escaped(&field.swift_name);
        let raw = format!("{}Value", safe_local(&field.swift_name));
        if matches!(field.ty, SwiftType::Optional(_)) {
            writeln!(
                output,
                "        if let {raw} = record.fields[{}] {{",
                field.label.id()
            )?;
            writeln!(
                output,
                "            self.{member} = {}",
                decode_expression(&field.ty, &raw, 3, Some(&definition.name))
            )?;
            output.push_str("        } else {\n");
            writeln!(output, "            self.{member} = nil")?;
            output.push_str("        }\n");
        } else {
            writeln!(
                output,
                "        guard let {raw} = record.fields[{}] else {{",
                field.label.id()
            )?;
            writeln!(
                output,
                "            throw ICClientError.invalidCandid(\"record field {} is missing\")",
                field.label.id()
            )?;
            output.push_str("        }\n");
            writeln!(
                output,
                "        self.{member} = {}",
                decode_expression(&field.ty, &raw, 2, Some(&definition.name))
            )?;
        }
    }
    output.push_str("    }\n\n    public var candidValue: CandidValue {\n");
    output.push_str("        .record(Self.fields, [\n");
    for field in fields {
        writeln!(
            output,
            "            {}: {},",
            field.label.id(),
            encode_expression(
                &field.ty,
                &format!("self.{}", escaped(&field.swift_name)),
                &definition.name,
                recursion_id
            )
        )?;
    }
    output.push_str("        ])\n    }\n}\n");
    Ok(())
}

fn render_variant(output: &mut String, definition: &Definition, cases: &[Case]) -> Result<()> {
    let indirect = if definition.recursive {
        "indirect "
    } else {
        ""
    };
    writeln!(
        output,
        "public {indirect}enum {}: CandidConvertible {{",
        escaped(&definition.name)
    )?;
    for case in cases {
        let name = escaped(&case.swift_name);
        match &case.payload {
            Some(payload) => writeln!(output, "    case {name}(value: {})", swift_type(payload))?,
            None => writeln!(output, "    case {name}")?,
        }
    }
    let recursion_id = recursion_id(&definition.name);
    output.push_str("\n    private static let fields: [CandidField] = [\n");
    for case in cases {
        let ty = case
            .payload
            .as_ref()
            .map(|ty| candid_type(ty, &definition.name, recursion_id))
            .unwrap_or_else(|| ".null".to_owned());
        writeln!(
            output,
            "        CandidField(id: {}, type: {ty}),",
            case.label.id()
        )?;
    }
    output.push_str("    ]\n\n");
    if definition.recursive {
        writeln!(
            output,
            "    public static let candidType = CandidType.recursive(id: {recursion_id}, body: .variant(fields))"
        )?;
    } else {
        output.push_str("    public static let candidType = CandidType.variant(fields)\n");
    }
    output.push_str("\n    public init(candidValue: CandidValue) throws {\n");
    output.push_str("        guard case .variant(let variant) = candidValue else {\n");
    output.push_str(
        "            throw ICClientError.invalidCandid(\"expected variant\")\n        }\n",
    );
    output.push_str("        switch variant.tag {\n");
    for case in cases {
        let name = escaped(&case.swift_name);
        writeln!(output, "        case {}:", case.label.id())?;
        match &case.payload {
            Some(payload) => writeln!(
                output,
                "            self = .{name}(value: {})",
                decode_expression(payload, "variant.value", 3, Some(&definition.name))
            )?,
            None => writeln!(output, "            self = .{name}")?,
        }
    }
    output.push_str("        default:\n            throw ICClientError.invalidCandid(\"unknown variant tag \\(variant.tag)\")\n        }\n    }\n");
    output.push_str("\n    public var candidValue: CandidValue {\n        switch self {\n");
    for case in cases {
        let name = escaped(&case.swift_name);
        match &case.payload {
            Some(payload) => {
                writeln!(output, "        case .{name}(let value):")?;
                writeln!(
                    output,
                    "            return .variant(try! CandidVariant(fields: Self.fields, tag: {}, value: {}))",
                    case.label.id(),
                    encode_expression(payload, "value", &definition.name, recursion_id)
                )?;
            }
            None => {
                writeln!(output, "        case .{name}:")?;
                writeln!(
                    output,
                    "            return .variant(try! CandidVariant(fields: Self.fields, tag: {}, value: .null))",
                    case.label.id()
                )?;
            }
        }
    }
    output.push_str("        }\n    }\n}\n");
    Ok(())
}

fn render_client(
    output: &mut String,
    canister: &Canister,
    support_owner: &str,
    includes_support: bool,
) -> Result<()> {
    for method in &canister.methods {
        render_method_boundary_types(output, canister, method)?;
    }
    writeln!(
        output,
        "\npublic struct {}: Sendable {{",
        escaped(&canister.client_name)
    )?;
    if includes_support {
        render_typed_decoder(output)?;
    }
    output.push_str("    public let client: ICClient\n    public let canisterId: String\n\n");
    match &canister.canister_id {
        Some(id) => writeln!(
            output,
            "    public init(client: ICClient, canisterId: String = \"{}\") {{",
            swift_string(id)
        )?,
        None => output.push_str("    public init(client: ICClient, canisterId: String) {\n"),
    }
    output.push_str("        self.client = client\n        self.canisterId = canisterId\n    }\n");
    for method in &canister.methods {
        render_method(output, canister, method, support_owner)?;
    }
    output.push_str("}\n");
    Ok(())
}

fn render_method_boundary_types(
    output: &mut String,
    canister: &Canister,
    method: &Method,
) -> Result<()> {
    let base = format!("{}{}", canister.name, type_identifier(&method.candid_name));
    if method.arguments.len() > 1 {
        render_tuple_struct(output, &format!("{base}Arguments"), &method.arguments)?;
    }
    if method.returns.len() > 1 {
        render_tuple_struct(output, &format!("{base}Result"), &method.returns)?;
    }
    Ok(())
}

fn render_tuple_struct(output: &mut String, name: &str, types: &[SwiftType]) -> Result<()> {
    writeln!(output, "\npublic struct {}: Sendable {{", escaped(name))?;
    for (index, ty) in types.iter().enumerate() {
        writeln!(output, "    public let value{index}: {}", swift_type(ty))?;
    }
    output.push_str("\n    public init(\n");
    for (index, ty) in types.iter().enumerate() {
        let comma = if index + 1 == types.len() { "" } else { "," };
        writeln!(output, "        value{index}: {}{comma}", swift_type(ty))?;
    }
    output.push_str("    ) {\n");
    for index in 0..types.len() {
        writeln!(output, "        self.value{index} = value{index}")?;
    }
    output.push_str("    }\n}\n");
    Ok(())
}

fn render_method(
    output: &mut String,
    canister: &Canister,
    method: &Method,
    support_owner: &str,
) -> Result<()> {
    let base = format!("{}{}", canister.name, type_identifier(&method.candid_name));
    let return_type = match method.returns.as_slice() {
        [] => "Void".to_owned(),
        [ty] => swift_type(ty),
        _ => format!("{base}Result"),
    };
    write!(output, "\n    public func {}(", escaped(&method.swift_name))?;
    match method.arguments.as_slice() {
        [] => {}
        [ty] => write!(output, "_ argument: {}", swift_type(ty))?,
        _ => write!(output, "_ arguments: {base}Arguments")?,
    }
    let has_argument = !method.arguments.is_empty();
    match method.kind {
        MethodKind::Query => {
            if has_argument {
                output.push_str(", ");
            }
            output.push_str("identity: ICAuthSession? = nil, effectiveCanisterId: String? = nil");
        }
        MethodKind::Update => {
            if has_argument {
                output.push_str(", ");
            }
            output.push_str("identity: ICAuthSession, effectiveCanisterId: String? = nil");
        }
    }
    writeln!(output, ") async throws -> {return_type} {{")?;

    match method.arguments.as_slice() {
        [] => output.push_str("        let candidArguments = CandidArguments()\n"),
        [_] => output.push_str(
            "        let candidArguments = CandidArguments([try CandidTypedValue(argument)])\n",
        ),
        types => {
            output.push_str("        let candidArguments = CandidArguments([\n");
            for index in 0..types.len() {
                writeln!(
                    output,
                    "            try CandidTypedValue(arguments.value{index}),"
                )?;
            }
            output.push_str("        ])\n");
        }
    }

    match method.kind {
        MethodKind::Query => {
            output.push_str("        let reply = try await client.queryCandid(\n");
            writeln!(
                output,
                "            method: \"{}\",",
                swift_string(&method.candid_name)
            )?;
            output.push_str("            arguments: candidArguments,\n            canisterId: canisterId,\n            effectiveCanisterId: effectiveCanisterId,\n            identity: identity\n        )\n");
        }
        MethodKind::Update => {
            output.push_str("        let reply = try await client.callCandid(\n");
            writeln!(
                output,
                "            method: \"{}\",",
                swift_string(&method.candid_name)
            )?;
            output.push_str("            arguments: candidArguments,\n            canisterId: canisterId,\n            effectiveCanisterId: effectiveCanisterId,\n            identity: identity\n        )\n");
        }
    }
    writeln!(
        output,
        "        guard reply.values.count == {} else {{",
        method.returns.len()
    )?;
    writeln!(
        output,
        "            throw ICClientError.invalidCandid(\"method {} expected {} reply values, received \\(reply.values.count)\")",
        swift_string(&method.candid_name),
        method.returns.len()
    )?;
    output.push_str("        }\n");
    match method.returns.as_slice() {
        [] => output.push_str("        return ()\n"),
        [ty] => writeln!(
            output,
            "        return try {}._ICBindgenSupport.decode(reply.values[0], as: {}.self, context: \"method {} reply value 0\")",
            escaped(support_owner),
            swift_type(ty),
            swift_string(&method.candid_name)
        )?,
        types => {
            writeln!(output, "        return {base}Result(")?;
            for (index, ty) in types.iter().enumerate() {
                let comma = if index + 1 == types.len() { "" } else { "," };
                writeln!(
                    output,
                    "            value{index}: try {}._ICBindgenSupport.decode(reply.values[{index}], as: {}.self, context: \"method {} reply value {index}\"){comma}",
                    escaped(support_owner),
                    swift_type(ty),
                    swift_string(&method.candid_name)
                )?;
            }
            output.push_str("        )\n");
        }
    }
    output.push_str("    }\n");
    Ok(())
}

fn swift_type(ty: &SwiftType) -> String {
    match ty {
        SwiftType::Bool => "Bool".into(),
        SwiftType::Nat => "CandidNat".into(),
        SwiftType::Int => "CandidInt".into(),
        SwiftType::Nat8 => "UInt8".into(),
        SwiftType::Nat16 => "UInt16".into(),
        SwiftType::Nat32 => "UInt32".into(),
        SwiftType::Nat64 => "UInt64".into(),
        SwiftType::Int8 => "Int8".into(),
        SwiftType::Int16 => "Int16".into(),
        SwiftType::Int32 => "Int32".into(),
        SwiftType::Int64 => "Int64".into(),
        SwiftType::Text => "String".into(),
        SwiftType::Blob => "Data".into(),
        SwiftType::Principal => "CandidPrincipal".into(),
        SwiftType::Null => "CandidNull".into(),
        SwiftType::Optional(child) => format!("{}?", swift_type(child)),
        SwiftType::Vector(child) => format!("[{}]", swift_type(child)),
        SwiftType::Named(name) => escaped(name),
    }
}

fn candid_type(ty: &SwiftType, recursive_name: &str, recursion_id: u32) -> String {
    match ty {
        SwiftType::Bool => ".bool".into(),
        SwiftType::Nat => ".nat".into(),
        SwiftType::Int => ".int".into(),
        SwiftType::Nat8 => ".nat8".into(),
        SwiftType::Nat16 => ".nat16".into(),
        SwiftType::Nat32 => ".nat32".into(),
        SwiftType::Nat64 => ".nat64".into(),
        SwiftType::Int8 => ".int8".into(),
        SwiftType::Int16 => ".int16".into(),
        SwiftType::Int32 => ".int32".into(),
        SwiftType::Int64 => ".int64".into(),
        SwiftType::Text => ".text".into(),
        SwiftType::Blob => ".vector(.nat8)".into(),
        SwiftType::Principal => ".principal".into(),
        SwiftType::Null => ".null".into(),
        SwiftType::Optional(child) => format!(
            ".optional({})",
            candid_type(child, recursive_name, recursion_id)
        ),
        SwiftType::Vector(child) => format!(
            ".vector({})",
            candid_type(child, recursive_name, recursion_id)
        ),
        SwiftType::Named(name) if name == recursive_name => format!(".reference({recursion_id})"),
        SwiftType::Named(name) => format!("{}.candidType", escaped(name)),
    }
}

fn encode_expression(
    ty: &SwiftType,
    value: &str,
    recursive_name: &str,
    recursion_id: u32,
) -> String {
    match ty {
        SwiftType::Optional(child) => format!(
            ".optional({}, {value}.map {{ {} }})",
            candid_type(child, recursive_name, recursion_id),
            encode_expression(child, "$0", recursive_name, recursion_id)
        ),
        SwiftType::Vector(child) => format!(
            ".vector({}, {value}.map {{ {} }})",
            candid_type(child, recursive_name, recursion_id),
            encode_expression(child, "$0", recursive_name, recursion_id)
        ),
        SwiftType::Blob => format!(".blob({value})"),
        _ => format!("{value}.candidValue"),
    }
}

fn decode_expression(
    ty: &SwiftType,
    value: &str,
    indent: usize,
    recursive_owner: Option<&str>,
) -> String {
    match ty {
        SwiftType::Optional(child) if contains_named(child, recursive_owner) => {
            let padding = "    ".repeat(indent);
            let inner = decode_expression(child, "item", indent + 1, recursive_owner);
            format!(
                "try {{ () throws -> {} in\n{padding}    guard case .optional(_, let wrapped) = {value} else {{\n{padding}        throw ICClientError.invalidCandid(\"expected optional\")\n{padding}    }}\n{padding}    guard let item = wrapped else {{ return nil }}\n{padding}    return {inner}\n{padding}}}()",
                swift_type(ty)
            )
        }
        SwiftType::Vector(child) if contains_named(child, recursive_owner) => {
            let padding = "    ".repeat(indent);
            let inner = decode_expression(child, "item", indent + 1, recursive_owner);
            format!(
                "try {{ () throws -> {} in\n{padding}    guard case .vector(_, let items) = {value} else {{\n{padding}        throw ICClientError.invalidCandid(\"expected vector\")\n{padding}    }}\n{padding}    return try items.map {{ item in {inner} }}\n{padding}}}()",
                swift_type(ty)
            )
        }
        _ => format!("try {}(candidValue: {value})", swift_type(ty)),
    }
}

fn contains_named(ty: &SwiftType, name: Option<&str>) -> bool {
    match (ty, name) {
        (SwiftType::Optional(child) | SwiftType::Vector(child), _) => contains_named(child, name),
        (SwiftType::Named(candidate), Some(name)) => candidate == name,
        _ => false,
    }
}

pub fn type_identifier(input: &str) -> String {
    let words = words(input);
    let mut result = String::new();
    for word in words {
        let mut characters = word.chars();
        if let Some(first) = characters.next() {
            result.extend(first.to_uppercase());
            result.extend(characters);
        }
    }
    if result.is_empty() {
        "Generated".into()
    } else if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("Type{result}")
    } else {
        result
    }
}

pub fn member_identifier(input: &str) -> String {
    let type_name = type_identifier(input);
    let mut characters = type_name.chars();
    let Some(first) = characters.next() else {
        return "value".into();
    };
    let mut result = first.to_lowercase().collect::<String>();
    result.extend(characters);
    if result.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("value{result}")
    } else {
        result
    }
}

fn words(input: &str) -> Vec<&str> {
    input
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|word| !word.is_empty())
        .collect()
}

fn escaped(identifier: &str) -> String {
    if swift_keywords().contains(identifier) {
        format!("`{identifier}`")
    } else {
        identifier.to_owned()
    }
}

fn safe_local(identifier: &str) -> String {
    let result = identifier.trim_matches('`');
    if swift_keywords().contains(result) {
        format!("{result}Field")
    } else {
        result.to_owned()
    }
}

fn swift_keywords() -> BTreeSet<&'static str> {
    [
        "associatedtype",
        "actor",
        "any",
        "async",
        "await",
        "borrowing",
        "break",
        "case",
        "catch",
        "class",
        "continue",
        "consuming",
        "default",
        "defer",
        "deinit",
        "do",
        "else",
        "enum",
        "extension",
        "fallthrough",
        "false",
        "fileprivate",
        "for",
        "func",
        "guard",
        "if",
        "import",
        "in",
        "init",
        "inout",
        "isolated",
        "internal",
        "is",
        "let",
        "nil",
        "nonisolated",
        "operator",
        "precedencegroup",
        "private",
        "protocol",
        "public",
        "repeat",
        "rethrows",
        "return",
        "self",
        "sending",
        "Self",
        "some",
        "static",
        "struct",
        "subscript",
        "super",
        "switch",
        "throw",
        "throws",
        "true",
        "try",
        "typealias",
        "var",
        "where",
        "while",
    ]
    .into_iter()
    .collect()
}

fn recursion_id(name: &str) -> u32 {
    candid_parser::idl_hash(name)
}

fn swift_string(value: &str) -> String {
    let mut result = String::new();
    for character in value.chars() {
        match character {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            '\u{2028}' | '\u{2029}' => {
                write!(result, "\\u{{{:X}}}", character as u32).unwrap();
            }
            character if character.is_control() => {
                write!(result, "\\u{{{:X}}}", character as u32).unwrap();
            }
            character => result.push(character),
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalizes_identifiers() {
        assert_eq!(type_identifier("ledger_tokens"), "LedgerTokens");
        assert_eq!(member_identifier("account_balance"), "accountBalance");
        assert_eq!(escaped("case"), "`case`");
    }

    #[test]
    fn escapes_unprintable_swift_string_characters() {
        assert_eq!(
            swift_string("a\u{0}\u{b}\u{2028}\u{2029}z"),
            "a\\u{0}\\u{B}\\u{2028}\\u{2029}z"
        );
    }
}
